### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by walterheck** [saagarjha/Jumpcut#1]
I'm not interested in building myself, but interested in a more up-to-date version and yours seems to be the most actively developed. Could you create a release here on github so I can just download binaries?

**Comment by saagarjha** [comment]
I'd be happy to. Unfortunately, I'm having some issues with uploading binaries at the moment, so once I hear back from Github support I'll be sure to put them up.

**Comment by saagarjha** [comment]
Done. Check out the [releases](https://github.com/saagarjha/Jumpcut/releases).

**Comment by walterheck** [comment]
Thanks a ton. My MBP died last week, so I'm using a M$ laptop until the new MBP's are released. Once that happens I'll come back here for sure :)
